In [ ]:
pip install pyspark==3.0.1 py4j==0.10.9

Collecting pyspark==3.0.1
  Downloading pyspark-3.0.1.tar.gz (204.2 MB)
     |████████████████████████████████| 204.2 MB 34 kB/s
Collecting py4j==0.10.9
  Downloading py4j-0.10.9-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 62.9 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.0.1-py2.py3-none-any.whl size=204612246 sha256=5053b16ea79aa8dd07b0dfbdf8ebba57b69d50b76012cfd2de878c02d2ffc8e4
  Stored in directory: /root/.cache/pip/wheels/5e/34/fa/b37b5cef503fc5148b478b2495043ba61b079120b7ff379f9b
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9 pyspark-3.0.1

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").appName('PySpark_Tutorial').getOrCreate()

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/players_20.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Columns: 104 entries, sofifa_id to rb
dtypes: float64(16), int64(45), object(43)
memory usage: 14.5+ MB

In [ ]:
import numpy as np 
import pandas as pd
from scipy.spatial import distance

In [ ]:
df1=df.iloc[:,0:20]
df2=df.iloc[:,20:40]
df3=df.iloc[:,40:60]
df4=df.iloc[:,60:80]
df5=df.iloc[:,80:]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   sofifa_id                 18278 non-null  int64
 1   player_url                18278 non-null  object
 2   short_name                18278 non-null  object
 3   long_name                 18278 non-null  object
 4   age                       18278 non-null  int64
 5   dob                       18278 non-null  object
 6   height_cm                 18278 non-null  int64
 7   weight_kg                 18278 non-null  int64
 8   nationality               18278 non-null  object
 9   club                      18278 non-null  object
 10  overall                   18278 non-null  int64
 11  potential                 18278 non-null  int64
 12  value_eur                 18278 non-null  int64
 13  wage_eur                  18278 non-null  int64
 14  player_positions          18278 non-null  object
 15  preferred_foot            18278 non-null  object
 16  international_reputation  18278 non-null  int64
 17  weak_foot                 18278 non-null  int64
 18  skill_moves               18278 non-null  int64
 19  work_rate                 18278 non-null  object
dtypes: int64(11), object(9)
memory usage: 2.8+ MB

In [ ]:
df1.describe().transpose()

                            count          mean  ...         75%          max
sofifa_id                 18278.0  2.197389e+05  ...   240795.75     252905.0
age                       18278.0  2.528329e+01  ...       29.00         42.0
height_cm                 18278.0  1.813622e+02  ...      186.00        205.0
weight_kg                 18278.0  7.527634e+01  ...       80.00        110.0
overall                   18278.0  6.624499e+01  ...       71.00         94.0
potential                 18278.0  7.154689e+01  ...       75.00         95.0
value_eur                 18278.0  2.484038e+06  ...  2100000.00  105500000.0
wage_eur                  18278.0  9.456943e+03  ...     8000.00     565000.0
international_reputation  18278.0  1.103184e+00  ...        1.00          5.0
weak_foot                 18278.0  2.944250e+00  ...        3.00          5.0
skill_moves               18278.0  2.368038e+00  ...        3.00          5.0

[11 rows x 8 columns]

In [ ]:
df1=df1.drop(['sofifa_id', 'player_url', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club', 'overall', 'potential',
       'value_eur', 'wage_eur','international_reputation','player_positions','preferred_foot'],axis=1)

In [ ]:
df1.head()

          short_name  weak_foot  skill_moves      work_rate
0           L. Messi          4            4     Medium/Low
1  Cristiano Ronaldo          4            5       High/Low
2          Neymar Jr          5            5    High/Medium
3           J. Oblak          3            1  Medium/Medium
4          E. Hazard          4            4    High/Medium

In [ ]:
df2=df2.drop(['body_type', 'real_face', 'release_clause_eur', 'team_jersey_number', 'loaned_from', 'joined',
       'contract_valid_until', 'nation_jersey_number',"nation_position",'player_tags','team_position','gk_diving', 'gk_handling', 'gk_kicking'],axis=1)

In [ ]:
df2.head()

   pace  shooting  passing  dribbling  defending  physic
0  87.0      92.0     92.0       96.0       39.0    66.0
1  90.0      93.0     82.0       89.0       35.0    78.0
2  91.0      85.0     87.0       95.0       32.0    58.0
3   NaN       NaN      NaN        NaN        NaN     NaN
4  91.0      83.0     86.0       94.0       35.0    66.0

In [ ]:
df2=df2.fillna(0)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pace       18278 non-null  float64
 1   shooting   18278 non-null  float64
 2   passing    18278 non-null  float64
 3   dribbling  18278 non-null  float64
 4   defending  18278 non-null  float64
 5   physic     18278 non-null  float64
dtypes: float64(6)
memory usage: 856.9 KB

In [ ]:
df3=df3.drop(["player_traits",'gk_reflexes', 'gk_speed', 'gk_positioning'],axis=1)

In [ ]:
df3=df3.fillna(0)

In [ ]:
df4=df4.drop(["ls","st"],axis=1)

In [ ]:
df=pd.concat([df1,df2,df3,df4],axis=1)

In [ ]:
df.head(20)

           short_name  weak_foot  ...  goalkeeping_positioning goalkeeping_reflexes
0            L. Messi          4  ...                       14                    8
1   Cristiano Ronaldo          4  ...                       14                   11
2           Neymar Jr          5  ...                       15                   11
3            J. Oblak          3  ...                       90                   89
4           E. Hazard          4  ...                        8                    8
5        K. De Bruyne          5  ...                       10                   13
6       M. ter Stegen          4  ...                       88                   90
7         V. van Dijk          3  ...                       11                   11
8           L. Modrić          4  ...                       14                    9
9            M. Salah          3  ...                       11                   14
10          K. Mbappé          4  ...                       11                    6
11       K. Koulibaly          3  ...                       13                    5
12            H. Kane          4  ...                       14                   11
13            Alisson          3  ...                       90                   89
14             De Gea          3  ...                       85                   92
15           N. Kanté          3  ...                        7                   10
16       G. Chiellini          3  ...                        4                    3
17          S. Agüero          4  ...                       11                   14
18       Sergio Ramos          3  ...                        7                   11
19          L. Suárez          4  ...                       33                   37

[20 rows x 44 columns]

In [ ]:
df["weak_foot"].unique()

array([4, 5, 3, 2, 1])

In [ ]:
def wr(x):
    x=x.split("/")
    return x[0]
df["offensive_work_rate"]=df["work_rate"].apply(lambda x: wr(x))

In [ ]:
df.head(20)

           short_name  weak_foot  ...  goalkeeping_reflexes offensive_work_rate
0            L. Messi          4  ...                     8              Medium
1   Cristiano Ronaldo          4  ...                    11                High
2           Neymar Jr          5  ...                    11                High
3            J. Oblak          3  ...                    89              Medium
4           E. Hazard          4  ...                     8                High
5        K. De Bruyne          5  ...                    13                High
6       M. ter Stegen          4  ...                    90              Medium
7         V. van Dijk          3  ...                    11              Medium
8           L. Modrić          4  ...                     9                High
9            M. Salah          3  ...                    14                High
10          K. Mbappé          4  ...                     6                High
11       K. Koulibaly          3  ...                     5              Medium
12            H. Kane          4  ...                    11                High
13            Alisson          3  ...                    89              Medium
14             De Gea          3  ...                    92              Medium
15           N. Kanté          3  ...                    10              Medium
16       G. Chiellini          3  ...                     3              Medium
17          S. Agüero          4  ...                    14                High
18       Sergio Ramos          3  ...                    11                High
19          L. Suárez          4  ...                    37                High

[20 rows x 45 columns]

In [ ]:
def wr(x):
    x=x.split("/")
    return x[1]
df["defensive_work_rate"]=df["work_rate"].apply(lambda x: wr(x))

In [ ]:
df.head()

          short_name  weak_foot  ...  offensive_work_rate defensive_work_rate
0           L. Messi          4  ...               Medium                 Low
1  Cristiano Ronaldo          4  ...                 High                 Low
2          Neymar Jr          5  ...                 High              Medium
3           J. Oblak          3  ...               Medium              Medium
4          E. Hazard          4  ...                 High              Medium

[5 rows x 46 columns]

In [ ]:
df=df.drop(["work_rate"],axis=1)

In [ ]:
df.head()

          short_name  weak_foot  ...  offensive_work_rate  defensive_work_rate
0           L. Messi          4  ...               Medium                  Low
1  Cristiano Ronaldo          4  ...                 High                  Low
2          Neymar Jr          5  ...                 High               Medium
3           J. Oblak          3  ...               Medium               Medium
4          E. Hazard          4  ...                 High               Medium

[5 rows x 45 columns]

In [ ]:
df["offensive_work_rate"].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [ ]:
def wr(x):
    if x=="High":
        return 0
    elif x=="Medium":
        return 1
    else:
        return 2
df["offensive_work_rate"]=df["offensive_work_rate"].apply(lambda x: wr(x))

In [ ]:
def wr(x):
    if x=="High":
        return 0
    elif x=="Medium":
        return 1
    else:
        return 2
df["defensive_work_rate"]=df["defensive_work_rate"].apply(lambda x: wr(x))

In [ ]:
df

              short_name  weak_foot  ...  offensive_work_rate  defensive_work_rate
0               L. Messi          4  ...                    1                    2
1      Cristiano Ronaldo          4  ...                    0                    2
2              Neymar Jr          5  ...                    0                    1
3               J. Oblak          3  ...                    1                    1
4              E. Hazard          4  ...                    0                    1
...                  ...        ...  ...                  ...                  ...
18273         Shao Shuai          3  ...                    1                    0
18274       Xiao Mingjie          2  ...                    1                    1
18275          Zhang Wei          2  ...                    2                    1
18276       Wang Haijian          2  ...                    2                    2
18277         Pan Ximing          3  ...                    1                    1

[18278 rows x 45 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   short_name                  18278 non-null  object
 1   weak_foot                   18278 non-null  int64
 2   skill_moves                 18278 non-null  int64
 3   pace                        18278 non-null  float64
 4   shooting                    18278 non-null  float64
 5   passing                     18278 non-null  float64
 6   dribbling                   18278 non-null  float64
 7   defending                   18278 non-null  float64
 8   physic                      18278 non-null  float64
 9   attacking_crossing          18278 non-null  int64
 10  attacking_finishing         18278 non-null  int64
 11  attacking_heading_accuracy  18278 non-null  int64
 12  attacking_short_passing     18278 non-null  int64
 13  attacking_volleys           18278 non-null  int64
 14  skill_dribbling             18278 non-null  int64
 15  skill_curve                 18278 non-null  int64
 16  skill_fk_accuracy           18278 non-null  int64
 17  skill_long_passing          18278 non-null  int64
 18  skill_ball_control          18278 non-null  int64
 19  movement_acceleration       18278 non-null  int64
 20  movement_sprint_speed       18278 non-null  int64
 21  movement_agility            18278 non-null  int64
 22  movement_reactions          18278 non-null  int64
 23  movement_balance            18278 non-null  int64
 24  power_shot_power            18278 non-null  int64
 25  power_jumping               18278 non-null  int64
 26  power_stamina               18278 non-null  int64
 27  power_strength              18278 non-null  int64
 28  power_long_shots            18278 non-null  int64
 29  mentality_aggression        18278 non-null  int64
 30  mentality_interceptions     18278 non-null  int64
 31  mentality_positioning       18278 non-null  int64
 32  mentality_vision            18278 non-null  int64
 33  mentality_penalties         18278 non-null  int64
 34  mentality_composure         18278 non-null  int64
 35  defending_marking           18278 non-null  int64
 36  defending_standing_tackle   18278 non-null  int64
 37  defending_sliding_tackle    18278 non-null  int64
 38  goalkeeping_diving          18278 non-null  int64
 39  goalkeeping_handling        18278 non-null  int64
 40  goalkeeping_kicking         18278 non-null  int64
 41  goalkeeping_positioning     18278 non-null  int64
 42  goalkeeping_reflexes        18278 non-null  int64
 43  offensive_work_rate         18278 non-null  int64
 44  defensive_work_rate         18278 non-null  int64
dtypes: float64(6), int64(38), object(1)
memory usage: 6.3+ MB

In [ ]:
X=df.drop(["short_name"],axis=1)

In [ ]:
X

       weak_foot  skill_moves  ...  offensive_work_rate  defensive_work_rate
0              4            4  ...                    1                    2
1              4            5  ...                    0                    2
2              5            5  ...                    0                    1
3              3            1  ...                    1                    1
4              4            4  ...                    0                    1
...          ...          ...  ...                  ...                  ...
18273          3            2  ...                    1                    0
18274          2            2  ...                    1                    1
18275          2            2  ...                    2                    1
18276          2            2  ...                    2                    2
18277          3            2  ...                    1                    1

[18278 rows x 44 columns]

In [ ]:

player_name="L. Messi"
p_ind=df[df["short_name"]==player_name].index[0]

In [ ]:
dist=[]
for i in range (0,len(X.index)):
    dist.append(distance.euclidean(X.iloc[p_ind].values,X.iloc[i].values))

In [ ]:
len(dist)

18278

In [ ]:
pd.Series(dist)

0          0.000000
1         62.345810
2         42.696604
3        385.159707
4         44.000000
            ...
18273    295.741441
18274    288.405964
18275    249.489479
18276    242.936206
18277    244.335834
Length: 18278, dtype: float64

In [ ]:
sn=df["short_name"].to_list()

In [ ]:
sim={"name":sn,"distance":dist}

In [ ]:
sim=pd.DataFrame(sim)

In [ ]:
sim.iloc[sim["distance"].sort_values().index].head(20)

                  name   distance
0             L. Messi   0.000000
2            Neymar Jr  42.696604
4            E. Hazard  44.000000
23           P. Dybala  50.249378
37             M. Reus  52.573758
9             M. Salah  57.131427
43              H. Son  58.343809
236    Ronaldo Cabrais  61.781874
1    Cristiano Ronaldo  62.345810
55             L. Sané  62.641839
17           S. Agüero  63.000000
230      W. Ben Yedder  63.229740
10           K. Mbappé  64.265076
154          R. Mahrez  64.498062
178      Marco Asensio  64.536811
198         F. Thauvin  64.614240
328         J. Sildero  65.421709
209            C. Vela  65.650590
68            Coutinho  65.795137
152           D. Tadić  66.445466

In [ ]:
from scipy import spatial
cossim=[]
for i in range (0,len(X.index)):
    cossim.append(1 - spatial.distance.cosine(X.iloc[p_ind].values,X.iloc[i].values))
pd.Series(cossim)
sim2={"name":sn,"cossim":cossim}
sim2=pd.DataFrame(sim2)

In [ ]:
sim2.iloc[sim2["cossim"].sort_values(ascending=False).index].head(20)

                 name    cossim
0            L. Messi  1.000000
2           Neymar Jr  0.996724
209           C. Vela  0.996668
604        A. Januzaj  0.996653
4           E. Hazard  0.996653
1822        Z. Labyad  0.996561
154         R. Mahrez  0.996507
178     Marco Asensio  0.996388
2401           Jurado  0.996384
991        F. Contedo  0.996297
2541         C. Ciano  0.996295
2564       R. Ghezzal  0.996241
790      A. Miranchuk  0.996212
23          P. Dybala  0.996131
985   Claudio Coíntra  0.996128
362         A. Ljajić  0.996090
2585    L. Villafañez  0.995719
433        Rony Lopes  0.995700
2048   Y. Konoplyanka  0.995536
230     W. Ben Yedder  0.995521

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
std=StandardScaler()

In [ ]:
X=std.fit_transform(X)

In [ ]:
cossim=[]
for i in range (0,len(X)):
    cossim.append(1 - spatial.distance.cosine(X[p_ind],X[i]))
pd.Series(cossim)
sim2={"name":sn,"cossim":cossim}
sim2=pd.DataFrame(sim2)

In [ ]:
sim2.iloc[sim2["cossim"].sort_values(ascending=False).index].head(10)

           name    cossim
0      L. Messi  1.000000
328  J. Sildero  0.974434
23    P. Dybala  0.953150
118   J. Brandt  0.950221
4     E. Hazard  0.949638
37      M. Reus  0.942950
152    D. Tadić  0.941752
109  K. Havertz  0.940555
46   K. Benzema  0.939710
998   D. Brooks  0.939594

In [ ]:
dist=[]
for i in range (0,len(X)):
    dist.append(distance.euclidean(X[p_ind],X[i]))
pd.Series(dist)
sim={"name":sn,"distance":dist}
sim=pd.DataFrame(sim)
sim.iloc[sim["distance"].sort_values().index].head(10)

              name  distance
0         L. Messi  0.000000
4        E. Hazard  3.846940
328     J. Sildero  4.041698
23       P. Dybala  4.045125
37         M. Reus  4.203896
2        Neymar Jr  4.376035
46      K. Benzema  4.494967
9         M. Salah  4.554290
10       K. Mbappé  4.580361
38   P. Aubameyang  4.601487